version: "3.8"

services:
  db:
    image: postgres:15
    container_name: wms-db
    restart: always
    environment:
      POSTGRES_USER: wms
      POSTGRES_PASSWORD: wms_password
      POSTGRES_DB: wms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
