name: WMS CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff pytest alembic psycopg2

    - name: Set up Database URL
      run: echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Run Database Migrations
      run: |
        alembic upgrade head

    - name: Auto-Fix Formatting (Black)
      run: |
        black src/
        git diff --quiet || (git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git commit -am "Auto-format code using Black" && git push)

    - name: Auto-Fix Linting (Ruff)
      run: |
        ruff check src/ --fix
        git diff --quiet || (git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git commit -am "Auto-fix linting issues using Ruff" && git push)

    - name: Run Tests (Pytest)
      run: |
        pytest tests/
