name: WMS CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install Dependencies
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install black flake8 pytest

            - name: Run Formatter (Black)
              run: |
                  pip install black
                  black --check src/
            - name: Run Linter
              run: |
                  pip install flake8
                  flake8 src/ --max-line-length=88
            - name: Run Tests
              run: |
                  pytest tests/
