name: WMS CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff pytest

    - name: Auto-Fix Formatting (Black)
      run: |
        black src/
        git diff --quiet || (git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git commit -am "Auto-format code using Black" && git push)

    - name: Auto-Fix Linting (Ruff)
      run: |
        ruff check src/ --fix
        git diff --quiet || (git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git commit -am "Auto-fix linting issues using Ruff" && git push)

    - name: Run Tests (Pytest)
      run: |
        pytest tests/
