name: WMS CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Formatter (Black)
      run: |
        pip install black
        black src/
        git diff --exit-code || (echo "Code is not formatted properly. Run 'black src/'" && exit 1)
    - name: Run Linter
      run: |
        pip install flake8
        flake8 src/

    - name: Run Tests
      run: |
        pytest tests/
